### ISSUE TITLE
Connection terminated at launch

### ISSUE THREAD

**Issue by asad0x01** [Yimura/FridaMgr#11]
First of all, thank you for the release. It makes the whole process easier now. Regarding the issue:
The connection terminates at launch ( I have only tried using it remotely; I'm sure it's the same for USB as well). Sometimes, the phone reboots.

Attached is the screenshot here.
<img width="572" alt="Screenshot 2024-11-20 at 11 57 31 AM" src="https://github.com/user-attachments/assets/9938c925-9af5-45f2-b793-7c5cb73906c6">

Device: OnePlus 7T
OS Version: Android 11
Build Number: Oxygen OS 11.0.9.1.HD65AA
Kernel: blu-spark 4.14.190
Magisk Version: 27.0
SELinux: Enforcing

Could it be because of the SELinux status? OxygenOS always had issues with Frida ( I have tried Magisk Frida before and have to run a bunch lot of commands every time to fix). But it works fine with LineageOS 21.

**Comment by Yimura** [comment]
Hey @asad0x01, I wasn't able to use Frida-Server at all on my device while testing. This happened because of a silent update Google pushed to the `com.google.android.art` package, after uninstalling that it suddenly was working again.

I've found the solution here: https://github.com/frida/frida/issues/2954#issuecomment-2337037812

If it's possible can you try to connect via USB first and if that isn't working please try to solution from the linked comment from the Frida repository.

**Comment by Yimura** [comment]
No response from author, closing this issue.
